apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: "dns-config"
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE","UPDATE"]
      resources:   ["pods"]
    namespaceSelector:
      matchExpressions:
      - key: "system"
        operator: DoesNotExist
  matchConditions:
  - name: exclude-annotation
    expression: '!object.metadata.annotations.exists(a, a.contains("splunk8s.io.dns/disable-config"))'
  - name: dnsOptions-not-exist
    expression: '!has(object.spec.dnsConfig)'
  failurePolicy: Fail
  reinvocationPolicy: Never
  mutations:
    - patchType: "JSONPatch"
      jsonPatch:
        expression: >
          [
            JSONPatch{
              op: "add", path: "/spec/dnsConfig", value:  Object.spec.dnsConfig{
                options:  [
                  Object.spec.dnsConfig.options{
                    name: "test-name",
                    value: "test-value"
                  }
                ]
              }
            }
          ]
    # - patchType: "JSONPatch"
    #   jsonPatch:
    #     expression: >
    #       [
    #         JSONPatch{
    #           op: "remove", path: "/spec/containers/0",
    #         }
    #       ]
        # expression: >
        #     Object{
        #         spec: Object.spec{
        #             containers: object.spec.containers.filter(c, !has(c.env)).map(c,
        #               Object.spec.containers{
        #                 name: c.name,
        #                 env: object.spec.containers.env.filter(c, c.name == "JAEGET_AGENT_HOST").map()
        # env: dyn(c.env).filter(c, c.name != "JAEGER_AGENT_HOST")
        #               }
        #             )
        #         }
        #     }

        # expression: >
        #   Object{
        #     spec: Object.spec{
        #       containers: object.spec.containers.filter(c, c.env.filter(c, c.name != "JAEGET_AGENT_HOST"))
        #     }
        #   }
---
# Policy Binding
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: "mutate-policy-binding"
spec:
  policyName: "dns-config"